// Cluster
export const SAVE_CLUSTER_INFO = 'SAVE_CLUSTER_INFO'
export const SAVE_CLUSTER_DETAIL_LOADING = 'SAVE_CLUSTER_DETAIL_LOADING'
export const SAVE_CLUSTER_BY_QUERY = 'SAVE_CLUSTER_BY_QUERY'
export const SAVE_CLUSTER_BY_QUERY_LOADING = 'SAVE_CLUSTER_BY_QUERY_LOADING'
